### ISSUE TITLE
Error when running lexer.js

### ISSUE THREAD

**Issue by snadi** [abhisheksoni27/lexer.js#12]
See attached. Run on a Ubuntu machine after installing node.js and npm and installing your module through npm install

<img width="1920" alt="screen shot 2018-01-08 at 2 44 24 pm" src="https://user-images.githubusercontent.com/2363957/34693910-82515a8a-f482-11e7-9672-2211fbb4fa53.png">

**Comment by snadi** [comment]
@abhisheksoni27

**Comment by abhisheksoni27** [comment]
@snadi  Bug confirmed. (See Travis CI: [Build 16](https://travis-ci.org/abhisheksoni27/lexer.js/jobs/326598925)) 

Node 5.x (and lower is not supported.)

I am updating the `Readme`

Meanwhile,  to confirm it on your side, can you post the output of `node -v`?

Please update Node to `>6.x`. If you are using brew, this is straightforward. Simply run: 
```bash
brew upgrade node
```

[This](https://stackoverflow.com/questions/8191459/how-do-i-update-node-js/12413591#12413591) might help.

**Comment by snadi** [comment]
It's v4.2.6

**Comment by abhisheksoni27** [comment]
Ah! I am sorry. For Ubuntu, you can check [this](https://askubuntu.com/a/548776/493027) answer. The instructions on the nodejs.org website are pretty good too.

Copied from source [Installing Node.js Ubuntu](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) : 

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by snadi** [comment]
Works now. I'll test it tomorrow then. Thanks!

**Comment by abhisheksoni27** [comment]
Great!
